server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:learning_db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
  h2:
    console:
      enabled: true
      path: /h2

jwt:
  secret: ryj
  get:
    token:
      uri: /authenticate
